
/*
  Map accessors and custom evaluators do not work together
  Map( this[ "x" ] custOp value ) fails.
  The custom evaluator is passed the map itself, rather than the value
  corresponding to the key.
*/

package openehr.test;

import java.util.*;
import org.drools.factmodel.traits.Alias

global java.util.List list;


declare org.drools.factmodel.MapCore  //what is this for
end


declare trait Citizen
@traitable
    citizenship : String = "Unknown"
end

declare trait Student extends Citizen
@propertyReactive
   ID : String = "412314" @Alias("personID")
   GPA : Double = 3.99
end

declare Person
@Traitable
    personID : String
    isStudent : boolean
end

declare trait Worker
@propertyReactive
    hasBenefits : Boolean = true
end


rule "1"
salience 1
no-loop
when
then
    Person p = new Person("1020",true);
    Map map = new HashMap();
    map.put("isEmpty",true);
    insert(p);
    insert(map);
    list.add("initialized");
end

rule "2"
salience 1
no-loop
when
    $stu : Person(isStudent == true)
    $map : Map(this["isEmpty"] == true)
then
    Student s = don( $stu , Student.class );
    $map.put("worker" , s);
    $map.put("isEmpty" , false);
    update($map);
    System.out.println("don: Person -> Student ");
    list.add("student is donned");
end

rule "3"
salience 1
no-loop
when
    $map : Map($stu : this["worker"] isA Student.class)
then
    Object obj = don( $map , Worker.class );
    System.out.println("don: Map -> Worker : "+obj);
    list.add("worker is donned");
end
